"""empty message

Revision ID: 020e0a5b0d17
Revises: 21f9c3f284f1
Create Date: 2020-11-13 21:22:39.060057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '020e0a5b0d17'
down_revision = '21f9c3f284f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_adr', sa.String(length=64), nullable=True))
    op.drop_column('courses', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('address', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('courses', 'course_adr')
    # ### end Alembic commands ###
