"""empty message

Revision ID: 0ad73ca3d680
Revises: 8fdc441a7c32
Create Date: 2020-12-08 20:22:17.106635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ad73ca3d680'
down_revision = '8fdc441a7c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student_course', sa.Column('course_sid', sa.Integer(), nullable=True))
    op.drop_constraint('tb_student_course_ibfk_1', 'tb_student_course', type_='foreignkey')
    op.create_foreign_key(None, 'tb_student_course', 'courses', ['course_sid'], ['id'])
    op.drop_column('tb_student_course', 'course_sid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student_course', sa.Column('course_sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_student_course', type_='foreignkey')
    op.create_foreign_key('tb_student_course_ibfk_1', 'tb_student_course', 'courses', ['course_sid'], ['id'])
    op.drop_column('tb_student_course', 'course_sid')
    # ### end Alembic commands ###
