"""empty message

Revision ID: 0d20539d37b2
Revises: e05ac5c0d1c5
Create Date: 2020-12-14 21:49:35.057857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d20539d37b2'
down_revision = 'e05ac5c0d1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_admin')
    # ### end Alembic commands ###
