"""empty message

Revision ID: 1254b6981df4
Revises: 819ee90e6c35
Create Date: 2020-11-19 23:31:51.314886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1254b6981df4'
down_revision = '819ee90e6c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('university', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'university')
    # ### end Alembic commands ###
