"""empty message

Revision ID: 21f9c3f284f1
Revises: 74529dd02db7
Create Date: 2020-11-13 20:52:26.727316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f9c3f284f1'
down_revision = '74529dd02db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('school', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'school')
    # ### end Alembic commands ###
