"""empty message

Revision ID: 21ffe45bbdd7
Revises: 738efdab68a2
Create Date: 2020-12-08 20:13:47.267723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21ffe45bbdd7'
down_revision = '738efdab68a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_course_id', table_name='courses')
    op.drop_column('courses', 'course_sid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_courses_course_id', 'courses', ['course_sid'], unique=True)
    # ### end Alembic commands ###
