"""'admin'

Revision ID: 27d167039cb3
Revises: 154ec69daa2d
Create Date: 2020-12-07 18:21:44.493506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27d167039cb3'
down_revision = '154ec69daa2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_sid'], unique=True)
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.create_index(op.f('ix_students_sid'), 'students', ['sid'], unique=True)
    op.drop_index('ix_students_username', table_name='students')
    op.add_column('teachers', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_teachers_sid'), 'teachers', ['sid'], unique=True)
    op.drop_index('ix_teachers_username', table_name='teachers')
    op.drop_column('teachers', 'tc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('tc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_teachers_username', 'teachers', ['username'], unique=False)
    op.drop_index(op.f('ix_teachers_sid'), table_name='teachers')
    op.drop_column('teachers', 'is_admin')
    op.create_index('ix_students_username', 'students', ['username'], unique=False)
    op.drop_index(op.f('ix_students_sid'), table_name='students')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    # ### end Alembic commands ###
