"""empty message

Revision ID: 3373e8cd37c6
Revises: 92661e5cc9b5
Create Date: 2020-12-14 11:12:24.027341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3373e8cd37c6'
down_revision = '92661e5cc9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('course_sid', table_name='records')
    op.drop_index('student_sid', table_name='records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('student_sid', 'records', ['student_sid'], unique=True)
    op.create_index('course_sid', 'records', ['course_sid'], unique=True)
    # ### end Alembic commands ###
