"""empty message

Revision ID: 388ade63e4ae
Revises: 21ffe45bbdd7
Create Date: 2020-12-08 20:14:33.484867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388ade63e4ae'
down_revision = '21ffe45bbdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_sid', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'courses', ['course_sid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    op.drop_column('courses', 'course_sid')
    # ### end Alembic commands ###
