"""empty message

Revision ID: 4a1097dc5c48
Revises: ba5df1d47260
Create Date: 2020-12-15 12:15:05.036418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1097dc5c48'
down_revision = 'ba5df1d47260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('largest_number', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('number_remaining', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'number_remaining')
    op.drop_column('courses', 'largest_number')
    # ### end Alembic commands ###
