"""empty message

Revision ID: 581668203b4f
Revises: 0ad73ca3d680
Create Date: 2020-12-13 20:38:06.339462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581668203b4f'
down_revision = '0ad73ca3d680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student_course', sa.Column('course_state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_student_course', 'course_state')
    # ### end Alembic commands ###
