"""empty message

Revision ID: 5a72da0352c8
Revises: 81fed7bb0518
Create Date: 2020-12-15 10:35:42.977050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a72da0352c8'
down_revision = '81fed7bb0518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('select_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'select_number')
    # ### end Alembic commands ###
