"""empty message

Revision ID: 608c1c639aba
Revises: 581668203b4f
Create Date: 2020-12-13 21:11:23.872552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '608c1c639aba'
down_revision = '581668203b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_state', sa.Boolean(), nullable=True))
    op.drop_column('tb_student_course', 'course_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student_course', sa.Column('course_state', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('courses', 'course_state')
    # ### end Alembic commands ###
