"""empty message

Revision ID: 6125497f669d
Revises: 946c9ebb7f61
Create Date: 2020-12-15 22:22:32.192158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6125497f669d'
down_revision = '946c9ebb7f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('course_state', sa.Boolean(), nullable=True))
    op.drop_column('records', 'select_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('select_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('records', 'course_state')
    # ### end Alembic commands ###
