"""empty message

Revision ID: 61ad5db806c3
Revises: a216fdce04a9
Create Date: 2020-12-15 11:00:08.175052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ad5db806c3'
down_revision = 'a216fdce04a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('select_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'select_number')
    # ### end Alembic commands ###
