"""empty message

Revision ID: 6b225158e748
Revises: 4a4e8f4ee754
Create Date: 2020-11-12 17:22:37.753649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b225158e748'
down_revision = '4a4e8f4ee754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('school', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('university', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'university')
    op.drop_column('students', 'school')
    # ### end Alembic commands ###
