"""'admin'

Revision ID: 738efdab68a2
Revises: 27d167039cb3
Create Date: 2020-12-07 23:14:50.754877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738efdab68a2'
down_revision = '27d167039cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_admin')
    # ### end Alembic commands ###
