"""empty message

Revision ID: 74529dd02db7
Revises: 6b225158e748
Create Date: 2020-11-13 20:50:56.326507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74529dd02db7'
down_revision = '6b225158e748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_name', sa.String(length=64), nullable=True))
    op.add_column('courses', sa.Column('course_time', sa.String(length=64), nullable=True))
    op.drop_column('courses', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('courses', 'course_time')
    op.drop_column('courses', 'course_name')
    # ### end Alembic commands ###
