"""empty message

Revision ID: 819ee90e6c35
Revises: 020e0a5b0d17
Create Date: 2020-11-13 22:11:24.012634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819ee90e6c35'
down_revision = '020e0a5b0d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_sid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_sid')
    # ### end Alembic commands ###
