"""empty message

Revision ID: 81fed7bb0518
Revises: 0d20539d37b2
Create Date: 2020-12-14 23:57:37.756501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fed7bb0518'
down_revision = '0d20539d37b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_delete')
    # ### end Alembic commands ###
