"""empty message

Revision ID: 92661e5cc9b5
Revises: 608c1c639aba
Create Date: 2020-12-14 11:00:52.808372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92661e5cc9b5'
down_revision = '608c1c639aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_sid', sa.String(length=64), nullable=True),
    sa.Column('student_sid', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_sid'),
    sa.UniqueConstraint('student_sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
