"""empty message

Revision ID: 946c9ebb7f61
Revises: 4a1097dc5c48
Create Date: 2020-12-15 15:16:36.407425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946c9ebb7f61'
down_revision = '4a1097dc5c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_finish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_finish')
    # ### end Alembic commands ###
