"""empty message

Revision ID: 95b0599b632d
Revises: a462fea92a22
Create Date: 2020-12-01 16:58:05.688920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95b0599b632d'
down_revision = 'a462fea92a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('book_describe', sa.Text(), nullable=True))
    op.drop_column('book', 'boo_describe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('boo_describe', mysql.TEXT(), nullable=True))
    op.drop_column('book', 'book_describe')
    # ### end Alembic commands ###
