"""'课程描述'

Revision ID: 9cf1bf0a9949
Revises: e6795a6f17b9
Create Date: 2020-11-30 16:04:47.458073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cf1bf0a9949'
down_revision = 'e6795a6f17b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_category')
    op.add_column('courses', sa.Column('course_describe', sa.Text(), nullable=True))
    op.add_column('courses', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('courses', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('teachers', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('teachers', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'update_time')
    op.drop_column('teachers', 'create_time')
    op.drop_column('students', 'update_time')
    op.drop_column('students', 'create_time')
    op.drop_column('courses', 'update_time')
    op.drop_column('courses', 'create_time')
    op.drop_column('courses', 'course_describe')
    op.create_table('info_category',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
