"""'书本'

Revision ID: a462fea92a22
Revises: ece82f072212
Create Date: 2020-12-01 11:05:02.532889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a462fea92a22'
down_revision = 'ece82f072212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_about', sa.Text(), nullable=True),
    sa.Column('boo_describe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'book', ['book_id'], ['id'])
    op.drop_column('courses', 'course_describe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_describe', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'book_id')
    op.drop_table('book')
    # ### end Alembic commands ###
