"""empty message

Revision ID: a7676e03ae3c
Revises: 675a0e5c28b1
Create Date: 2020-12-20 17:50:59.155154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7676e03ae3c'
down_revision = '675a0e5c28b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student_course', sa.Column('course_sid', sa.Integer(), nullable=True))
    op.drop_constraint('tb_student_course_ibfk_3', 'tb_student_course', type_='foreignkey')
    op.create_foreign_key(None, 'tb_student_course', 'courses', ['course_sid'], ['id'])
    op.drop_column('tb_student_course', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student_course', sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tb_student_course', type_='foreignkey')
    op.create_foreign_key('tb_student_course_ibfk_3', 'tb_student_course', 'courses', ['course_id'], ['id'])
    op.drop_column('tb_student_course', 'course_sid')
    # ### end Alembic commands ###
