"""empty message

Revision ID: b0cf6b9fcaff
Revises: 69f6212906ea
Create Date: 2020-11-20 14:38:38.998310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0cf6b9fcaff'
down_revision = '69f6212906ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('teacher', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
