"""empty message

Revision ID: b9cec8294893
Revises: 52f40848490f
Create Date: 2020-11-29 20:34:18.673527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cec8294893'
down_revision = '52f40848490f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('test', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'test')
    # ### end Alembic commands ###
