"""empty message

Revision ID: ba5df1d47260
Revises: f9b6e5b7e53c
Create Date: 2020-12-15 11:02:16.182378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5df1d47260'
down_revision = 'f9b6e5b7e53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('select_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'select_number')
    # ### end Alembic commands ###
