"""empty message

Revision ID: c44e46438aa7
Revises: 2632f2a9638e
Create Date: 2020-11-27 17:43:55.398297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44e46438aa7'
down_revision = '2632f2a9638e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    op.add_column('teachers', sa.Column('avatar_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'avatar_url')
    op.drop_column('students', 'avatar_url')
    # ### end Alembic commands ###
