"""'学生课程多对多'

Revision ID: e5e61e07c543
Revises: 1254b6981df4
Create Date: 2020-11-20 09:55:31.819366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e61e07c543'
down_revision = '1254b6981df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_student_course',
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_sid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_sid'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_student_course')
    # ### end Alembic commands ###
