"""'书本图片'

Revision ID: ece82f072212
Revises: 9cf1bf0a9949
Create Date: 2020-11-30 16:16:59.833653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece82f072212'
down_revision = '9cf1bf0a9949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('course_avatar', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_avatar')
    # ### end Alembic commands ###
